/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Divider, Flex, SwitchField, Text, View } from "@aws-amplify/ui-react";
import { MenuButton38716751 as MenuButtonCustom } from "./MenuButton38716751";
export default function ContactCenterUI(props) {
  const { contactcenter, overrides, ...rest } = props;
  return (
    <Flex
      gap="11px"
      direction="column"
      width="751px"
      height="606px"
      justifyContent="flex-start"
      alignItems="flex-start"
      position="relative"
      padding="30px 20px 30px 20px"
      backgroundColor="rgba(233,249,252,1)"
      {...getOverrideProps(overrides, "ContactCenterUI")}
      {...rest}
    >
      <Flex
        gap="135px"
        direction="row"
        width="unset"
        height="unset"
        justifyContent="space-between"
        alignItems="flex-start"
        overflow="hidden"
        shrink="0"
        alignSelf="stretch"
        position="relative"
        padding="9px 0px 9px 0px"
        {...getOverrideProps(overrides, "headerbar")}
      >
        <Flex
          gap="0"
          direction="column"
          width="unset"
          height="unset"
          justifyContent="flex-start"
          alignItems="flex-start"
          overflow="hidden"
          shrink="0"
          position="relative"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "titlesection")}
        >
          <Text
            fontFamily="Inter"
            fontSize="24px"
            fontWeight="700"
            color="rgba(0,0,0,1)"
            lineHeight="32px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children={contactcenter?.ccname}
            {...getOverrideProps(overrides, "Single Billing Office")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="32px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children={contactcenter?.mainnumber}
            {...getOverrideProps(overrides, "713-366-5600")}
          ></Text>
        </Flex>
        <Flex
          gap="0"
          direction="column"
          width="unset"
          height="unset"
          justifyContent="flex-start"
          alignItems="flex-start"
          shrink="0"
          position="relative"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "statesection")}
        >
          <Text
            fontFamily="Inter"
            fontSize="24px"
            fontWeight="700"
            color="rgba(0,0,0,1)"
            lineHeight="32px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Current State"
            {...getOverrideProps(overrides, "Current State")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="20px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="32px"
            textAlign="center"
            display="block"
            direction="column"
            justifyContent="unset"
            width="unset"
            height="unset"
            gap="unset"
            alignItems="unset"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Open"
            {...getOverrideProps(overrides, "Open38746979")}
          ></Text>
        </Flex>
      </Flex>
      <Flex
        gap="0"
        direction="column"
        width="unset"
        height="unset"
        justifyContent="flex-start"
        alignItems="flex-start"
        overflow="hidden"
        shrink="0"
        alignSelf="stretch"
        position="relative"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "border3869763")}
      >
        <Divider
          width="706px"
          height="3px"
          shrink="0"
          size="small"
          orientation="horizontal"
          {...getOverrideProps(overrides, "Divider3869742")}
        ></Divider>
      </Flex>
      <Flex
        gap="5px"
        direction="row"
        width="unset"
        height="unset"
        justifyContent="flex-start"
        alignItems="flex-start"
        shrink="0"
        alignSelf="stretch"
        position="relative"
        border="1px SOLID rgba(188,236,245,1)"
        padding="13px 0px 13px 0px"
        {...getOverrideProps(overrides, "welcomepromptsec")}
      >
        <Text
          fontFamily="Inter"
          fontSize="15px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="18.15340805053711px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="687px"
          height="unset"
          gap="unset"
          alignItems="unset"
          shrink="0"
          alignSelf="stretch"
          position="relative"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children={contactcenter?.welcomeprompt}
          {...getOverrideProps(
            overrides,
            'Thank you for calling Houston Methodist, Customer Service. <break time="1s"/> If this is an emergency, please hangup, and dial 911. <break time="1s"/>This call may be recorded for quality and training purposes. <break time="1s"/>'
          )}
        ></Text>
      </Flex>
      <Flex
        gap="1px"
        direction="row"
        width="unset"
        height="unset"
        justifyContent="space-between"
        alignItems="flex-start"
        shrink="0"
        alignSelf="stretch"
        position="relative"
        padding="10px 0px 10px 0px"
        {...getOverrideProps(overrides, "mainivrcontent")}
      >
        <Flex
          gap="11px"
          direction="row"
          width="346px"
          height="249px"
          justifyContent="flex-start"
          alignItems="flex-start"
          shrink="0"
          position="relative"
          padding="6px 6px 6px 6px"
          backgroundColor="rgba(64,170,191,1)"
          {...getOverrideProps(overrides, "ivrbuttonsec")}
        >
          <MenuButtonCustom
            display="flex"
            gap="10px"
            direction="row"
            width="104px"
            height="50px"
            justifyContent="center"
            alignItems="center"
            shrink="0"
            position="relative"
            borderRadius="7px"
            padding="10px 0px 10px 0px"
            backgroundColor="rgba(255,255,255,1)"
            state="Default"
            {...getOverrideProps(overrides, "MenuButton38716751")}
          ></MenuButtonCustom>
          <MenuButtonCustom
            display="flex"
            gap="10px"
            direction="row"
            width="104px"
            height="50px"
            justifyContent="center"
            alignItems="center"
            shrink="0"
            position="relative"
            borderRadius="7px"
            padding="10px 0px 10px 0px"
            backgroundColor="rgba(255,255,255,1)"
            state="Default"
            {...getOverrideProps(overrides, "MenuButton38716767")}
          ></MenuButtonCustom>
          <MenuButtonCustom
            display="flex"
            gap="10px"
            direction="row"
            width="104px"
            height="50px"
            justifyContent="center"
            alignItems="center"
            shrink="0"
            position="relative"
            borderRadius="7px"
            padding="10px 0px 10px 0px"
            backgroundColor="rgba(255,255,255,1)"
            state="Default"
            {...getOverrideProps(overrides, "MenuButton38716903")}
          ></MenuButtonCustom>
          <MenuButtonCustom
            display="flex"
            gap="10px"
            direction="row"
            width="104px"
            height="50px"
            justifyContent="center"
            alignItems="center"
            shrink="0"
            position="relative"
            borderRadius="7px"
            padding="10px 0px 10px 0px"
            backgroundColor="rgba(255,255,255,1)"
            state="Default"
            {...getOverrideProps(overrides, "MenuButton38716783")}
          ></MenuButtonCustom>
          <MenuButtonCustom
            display="flex"
            gap="10px"
            direction="row"
            width="104px"
            height="50px"
            justifyContent="center"
            alignItems="center"
            shrink="0"
            position="relative"
            borderRadius="7px"
            padding="10px 0px 10px 0px"
            backgroundColor="rgba(255,255,255,1)"
            state="Default"
            {...getOverrideProps(overrides, "MenuButton38716791")}
          ></MenuButtonCustom>
          <MenuButtonCustom
            display="flex"
            gap="10px"
            direction="row"
            width="104px"
            height="50px"
            justifyContent="center"
            alignItems="center"
            shrink="0"
            position="relative"
            borderRadius="7px"
            padding="10px 0px 10px 0px"
            backgroundColor="rgba(255,255,255,1)"
            state="Default"
            {...getOverrideProps(overrides, "MenuButton38716799")}
          ></MenuButtonCustom>
          <MenuButtonCustom
            display="flex"
            gap="10px"
            direction="row"
            width="104px"
            height="50px"
            justifyContent="center"
            alignItems="center"
            shrink="0"
            position="relative"
            borderRadius="7px"
            padding="10px 0px 10px 0px"
            backgroundColor="rgba(255,255,255,1)"
            state="Default"
            {...getOverrideProps(overrides, "MenuButton38716807")}
          ></MenuButtonCustom>
          <MenuButtonCustom
            display="flex"
            gap="10px"
            direction="row"
            width="104px"
            height="50px"
            justifyContent="center"
            alignItems="center"
            shrink="0"
            position="relative"
            borderRadius="7px"
            padding="10px 0px 10px 0px"
            backgroundColor="rgba(255,255,255,1)"
            state="Default"
            {...getOverrideProps(overrides, "MenuButton38716832")}
          ></MenuButtonCustom>
          <MenuButtonCustom
            display="flex"
            gap="10px"
            direction="row"
            width="104px"
            height="50px"
            justifyContent="center"
            alignItems="center"
            shrink="0"
            position="relative"
            borderRadius="7px"
            padding="10px 0px 10px 0px"
            backgroundColor="rgba(255,255,255,1)"
            state="Default"
            {...getOverrideProps(overrides, "MenuButton38716840")}
          ></MenuButtonCustom>
          <View
            width="104px"
            height="50px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            overflow="hidden"
            shrink="0"
            position="relative"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, "blanksec")}
          ></View>
          <MenuButtonCustom
            display="flex"
            gap="10px"
            direction="row"
            width="104px"
            height="50px"
            justifyContent="center"
            alignItems="center"
            shrink="0"
            position="relative"
            borderRadius="7px"
            padding="10px 0px 10px 0px"
            backgroundColor="rgba(255,255,255,1)"
            state="Default"
            {...getOverrideProps(overrides, "MenuButton38611821")}
          ></MenuButtonCustom>
        </Flex>
        <Flex
          gap="1px"
          direction="row"
          width="358px"
          height="unset"
          justifyContent="space-between"
          alignItems="flex-start"
          shrink="0"
          alignSelf="stretch"
          position="relative"
          padding="0px 0px 0px 0px"
          backgroundColor="rgba(255,255,255,1)"
          {...getOverrideProps(overrides, "todsec")}
        >
          <Flex
            gap="5px"
            direction="column"
            width="unset"
            height="unset"
            justifyContent="flex-start"
            alignItems="flex-start"
            overflow="hidden"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="8px 6px 8px 6px"
            {...getOverrideProps(overrides, "daysec")}
          >
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="700"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Days"
              {...getOverrideProps(overrides, "Days")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="34px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children={contactcenter?.daysopen}
              {...getOverrideProps(overrides, "MON")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="34px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children={contactcenter?.daysopen}
              {...getOverrideProps(overrides, "TUE")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="34px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="WED"
              {...getOverrideProps(overrides, "WED")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="34px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="THU"
              {...getOverrideProps(overrides, "THU")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="34px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="FRI"
              {...getOverrideProps(overrides, "FRI")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="34px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="SAT"
              {...getOverrideProps(overrides, "SAT")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="34px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="SUN"
              {...getOverrideProps(overrides, "SUN")}
            ></Text>
          </Flex>
          <Flex
            gap="5px"
            direction="column"
            width="unset"
            height="unset"
            justifyContent="flex-start"
            alignItems="flex-start"
            overflow="hidden"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="8px 6px 8px 6px"
            {...getOverrideProps(overrides, "openttodsec")}
          >
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="700"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Open"
              {...getOverrideProps(overrides, "Open38726942")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="8:00 AM"
              {...getOverrideProps(overrides, "8:00 AM38726943")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="8:00 AM"
              {...getOverrideProps(overrides, "8:00 AM38726944")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="8:00 AM"
              {...getOverrideProps(overrides, "8:00 AM38726945")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="8:00 AM"
              {...getOverrideProps(overrides, "8:00 AM38726946")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="8:00 AM"
              {...getOverrideProps(overrides, "8:00 AM38726947")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Closed"
              {...getOverrideProps(overrides, "Closed38726948")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Closed"
              {...getOverrideProps(overrides, "Closed38726949")}
            ></Text>
          </Flex>
          <Flex
            gap="5px"
            direction="column"
            width="unset"
            height="unset"
            justifyContent="flex-start"
            alignItems="flex-start"
            overflow="hidden"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="8px 6px 8px 6px"
            {...getOverrideProps(overrides, "2ndclosettodsec")}
          >
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="700"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="2nd Close"
              {...getOverrideProps(overrides, "2nd Close")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="11:30 AM"
              {...getOverrideProps(overrides, "11:30 AM38746962")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="11:30 AM"
              {...getOverrideProps(overrides, "11:30 AM38746963")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="11:30 AM"
              {...getOverrideProps(overrides, "11:30 AM38746964")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="11:30 AM"
              {...getOverrideProps(overrides, "11:30 AM38746965")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="11:30 AM"
              {...getOverrideProps(overrides, "11:30 AM38746966")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="NA"
              {...getOverrideProps(overrides, "NA38746967")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="NA"
              {...getOverrideProps(overrides, "NA38746968")}
            ></Text>
          </Flex>
          <Flex
            gap="5px"
            direction="column"
            width="unset"
            height="unset"
            justifyContent="flex-start"
            alignItems="flex-start"
            overflow="hidden"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="8px 6px 8px 6px"
            {...getOverrideProps(overrides, "closetodsec38746950")}
          >
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="700"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="2nd Open"
              {...getOverrideProps(overrides, "2nd Open")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="1:30 PM"
              {...getOverrideProps(overrides, "1:30 PM38746952")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="1:30 PM"
              {...getOverrideProps(overrides, "1:30 PM38746953")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="1:30 PM"
              {...getOverrideProps(overrides, "1:30 PM38746954")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="1:30 PM"
              {...getOverrideProps(overrides, "1:30 PM38746955")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="1:30 PM"
              {...getOverrideProps(overrides, "1:30 PM38746956")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="NA"
              {...getOverrideProps(overrides, "NA38746957")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="NA"
              {...getOverrideProps(overrides, "NA38746958")}
            ></Text>
          </Flex>
          <Flex
            gap="5px"
            direction="column"
            width="unset"
            height="unset"
            justifyContent="flex-start"
            alignItems="flex-start"
            overflow="hidden"
            shrink="0"
            alignSelf="stretch"
            position="relative"
            padding="8px 6px 8px 6px"
            {...getOverrideProps(overrides, "closetodsec38746969")}
          >
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="700"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="unset"
              height="unset"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Close"
              {...getOverrideProps(overrides, "Close")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="5:00 PM"
              {...getOverrideProps(overrides, "5:00 PM38746971")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="5:00 PM"
              {...getOverrideProps(overrides, "5:00 PM38746972")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="5:00 PM"
              {...getOverrideProps(overrides, "5:00 PM38746973")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="5:00 PM"
              {...getOverrideProps(overrides, "5:00 PM38746974")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="5:00 PM"
              {...getOverrideProps(overrides, "5:00 PM38746975")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Closed"
              {...getOverrideProps(overrides, "Closed38746976")}
            ></Text>
            <Text
              fontFamily="Inter"
              fontSize="12px"
              fontWeight="400"
              color="rgba(0,0,0,1)"
              lineHeight="32px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="65px"
              height="21px"
              gap="unset"
              alignItems="unset"
              shrink="0"
              position="relative"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children="Closed"
              {...getOverrideProps(overrides, "Closed38746977")}
            ></Text>
          </Flex>
        </Flex>
      </Flex>
      <Flex
        gap="0"
        direction="column"
        width="unset"
        height="unset"
        justifyContent="flex-start"
        alignItems="flex-start"
        overflow="hidden"
        shrink="0"
        alignSelf="stretch"
        position="relative"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "border38746981")}
      >
        <Divider
          width="706px"
          height="3px"
          shrink="0"
          size="small"
          orientation="horizontal"
          {...getOverrideProps(overrides, "Divider38746982")}
        ></Divider>
      </Flex>
      <Flex
        gap="7px"
        direction="row"
        width="unset"
        height="unset"
        justifyContent="center"
        alignItems="center"
        shrink="0"
        position="relative"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "altmenus")}
      >
        <SwitchField
          width="unset"
          height="unset"
          label="Off"
          shrink="0"
          size="default"
          defaultChecked={false}
          isDisabled={false}
          labelPosition="start"
          {...getOverrideProps(overrides, "SwitchField")}
        ></SwitchField>
        <MenuButtonCustom
          display="flex"
          gap="5px"
          direction="row"
          width="110px"
          height="50px"
          justifyContent="center"
          alignItems="center"
          shrink="0"
          position="relative"
          borderRadius="7px"
          padding="10px 0px 10px 0px"
          backgroundColor="rgba(125,214,232,1)"
          state="Default"
          {...getOverrideProps(overrides, "MenuButton3878751")}
        ></MenuButtonCustom>
        <MenuButtonCustom
          display="flex"
          gap="5px"
          direction="row"
          width="110px"
          height="50px"
          justifyContent="center"
          alignItems="center"
          shrink="0"
          position="relative"
          borderRadius="7px"
          padding="10px 0px 10px 0px"
          backgroundColor="rgba(125,214,232,1)"
          state="Default"
          {...getOverrideProps(overrides, "MenuButton3878759")}
        ></MenuButtonCustom>
        <MenuButtonCustom
          display="flex"
          gap="5px"
          direction="row"
          width="110px"
          height="50px"
          justifyContent="center"
          alignItems="center"
          shrink="0"
          position="relative"
          borderRadius="7px"
          padding="10px 0px 10px 0px"
          backgroundColor="rgba(125,214,232,1)"
          state="Default"
          {...getOverrideProps(overrides, "MenuButton3878767")}
        ></MenuButtonCustom>
      </Flex>
    </Flex>
  );
}
